#!/bin/sh

export DESGW_DATA_DIR="data/"
export PYTHONPATH="./python/:/data/des41.a/data/desgw/osgsetup/eeups/fnaleups/Linux64/lxml/v3.4.4/lib/python/:$PYTHONPATH"

umask 002

echo ''
echo ''
echo "Setting up Python environment..."

source /cvmfs/des.opensciencegrid.org/eeups/startupcachejob21i.sh
export EUPS_PATH=${EUPS_PATH}:/data/des41.a/data/desgw/osgsetup/eeups/fnaleups
setup --nolocks pyslalib

export PATH=/cvmfs/des.opensciencegrid.org/fnal/anaconda2/bin:$PATH
source activate des18a

unsetup numpy

#setup python
#setup numpy
#setup scipy
#setup matplotlib
#setup astropy
#setup fitsio
#setup yaml
#setup pygcn
#setup easyaccess
###s#etup healpy #MUST BE LAST
